/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import java.util.Arrays;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TebakArtis extends javax.swing.JFrame {
 String[] namaNama = {"Angelina", "Rina",
            "Dewi", "Chelsea",
            "Raisa", "Sheina", "Puspa",
            "Sandora"};
 String soal;
 int angka = 5;
    
    public TebakArtis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        petunjuk = new javax.swing.JLabel();
        inputanTextField = new javax.swing.JTextField();
        cekButton = new javax.swing.JButton();
        hasilTextField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tebak Nama Artis Dibawah");

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        petunjuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        petunjuk.setText("Klik Tombol Mulai Untuk Memulai Permainan");

        inputanTextField.setEditable(false);
        inputanTextField.setEnabled(false);
        inputanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputanTextFieldActionPerformed(evt);
            }
        });

        cekButton.setText("Cek");
        cekButton.setEnabled(false);
        cekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(petunjuk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(mulaiButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(inputanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(cekButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(petunjuk)
                .addGap(31, 31, 31)
                .addComponent(mulaiButton)
                .addGap(31, 31, 31)
                .addComponent(inputanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekButton)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
         soal = namaArtis().toLowerCase();
        inputanTextField.setText(null);
        hasilTextField.setText("SOAL : "+acakArtis().toUpperCase());
       inputanTextField.setEditable(true);
       inputanTextField.setEnabled(true);
       cekButton.setEnabled(true);
       mulaiButton.setVisible(false);
       cekButton.setVisible(true);
       angka = 5;
       
        
    }//GEN-LAST:event_mulaiButtonActionPerformed

    
    private String namaArtis() {
       
        double namaSaja = Math.random() * 8;
        double nilai = Math.floor(namaSaja);
        String pilihNama = namaNama[(int) nilai];
        return pilihNama;
    }
    
    private String acakArtis () {
        char[] hurufNama = soal.toCharArray();
        Arrays.sort(hurufNama);
        String nama = new String(hurufNama);
        return nama;
    }
    
   
    
    private void inputanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputanTextFieldActionPerformed

    private void cekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekButtonActionPerformed
        // TODO add your handling code here:
        
        String tebakan = inputanTextField.getText();
        angka--;
        if (tebakan.equalsIgnoreCase(soal)) {
            hasilTextField.setText("Anda Berhasil ! ");
            inputanTextField.setEditable(false);
            inputanTextField.setEnabled(false);
            mulaiButton.setVisible(true);
            cekButton.setEnabled(false);
        }else {
            hasilTextField.setText("Anda Salah, Silahkan Coba Lagi ! --> SOAL : "+acakArtis().toUpperCase()+
                    " Kesempatan : " +angka);
            inputanTextField.setText(null);
        } if (angka == 0) {
            JOptionPane.showMessageDialog(rootPane, "MAAF, Kesempatan Anda Sudah Habis !!");
            mulaiButton.setVisible(true);
        }
    }//GEN-LAST:event_cekButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakArtis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakArtis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakArtis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakArtis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakArtis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekButton;
    private javax.swing.JLabel hasilTextField;
    private javax.swing.JTextField inputanTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JLabel petunjuk;
    // End of variables declaration//GEN-END:variables
}
